# Generated by Django 2.0.3 on 2020-06-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='code',
            field=models.IntegerField(),
        ),
    ]
